# Naive Bayes - Class Exercise 2

## Introduction

## Metadata (Data Dictionary)

| No.| Variable | Data Type | Description |
|----|----------|-----------|-------------|
| 1  | customerID | string | ID of the customer |
| 2  | gender | string | Gender of the customer |
| 3  | SeniorCitizen | string | Whether the customer is a senior citizen (1) or not (0) |
| 4  | Partner | string | Whether the customer has a partner |
| 5  | Dependents | string | Whether the customer has dependent(s) |
| 6  | tenure | int | The duration as a customer (months) |
| 7  | PhoneService | string | Whether the customer subscribed to the phone service |
| 8  | MultipleLines | string | Whether the customer subscribed to multiple phone services |
| 9  | InternetService | string | Type of Internet Service |
| 10 | OnlineSecurity | string | Whether the customer subscribed to online security |
| 11 | OnlineBackup | string | Whether the customer subscribed to online backup |
| 12 | DeviceProtection | string | Whether the customer subscribed to online device protection |
| 13 | TechSupport | string | Whether the customer subscribed to technical support |
| 14 | StreamingTV | string | Whether the customer subscribed to streaming TV |
| 15 | StreamingMovies | string | Whether the customer subscribed to streaming movies |
| 16 | Contract | string | Type of Contract |
| 17 | PaperlessBilling | string | Whether the customer activated paperless billing |
| 18 | PaymentMethod | string | Payment method of the customer |
| 19 | MonthlyCharges | float | Monthly charge of the customer |
| 20 | TotalCharges | float | Total Charges of the customer |
| 21 | Churn | string | Whether the customer left within the last month or not |


## Import necessary libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import Data

<font color=red><b>Action</b>: Load the data file and check against the metadata.

In [2]:
df = pd.read_csv('Customer-Churn-Telco.csv')
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No     1.0   
1     5575-GNVDE    Male              0      No         No    34.0   
2     3668-QPYBK    Male              0      No         No     2.0   
3     7795-CFOCW    Male              0      No         No    45.0   
4     9237-HQITU  Female              0      No         No     2.0   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes    24.0   
7039  2234-XADUH  Female              0     Yes        Yes    72.0   
7040  4801-JZAZL  Female              0     Yes        Yes    11.0   
7041  8361-LTMKD    Male              1     Yes         No     4.0   
7042  3186-AJIEK    Male              0      No         No    66.0   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No         NaN          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [3]:
df['SeniorCitizen'] = df['SeniorCitizen'].astype('object')

In [4]:
label = 'Churn'
not_features = [label, 'customerID']
features = [feature for feature in list(df) if feature not in not_features]
features

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges']

In [5]:
numeric_features = [feature for feature in features if feature in list(df.describe())]
non_numeric_features = [feature for feature in features if feature not in list(df.describe())]
numeric_features, non_numeric_features

(['tenure', 'MonthlyCharges'],
 ['gender',
  'SeniorCitizen',
  'Partner',
  'Dependents',
  'PhoneService',
  'MultipleLines',
  'InternetService',
  'OnlineSecurity',
  'OnlineBackup',
  'DeviceProtection',
  'TechSupport',
  'StreamingTV',
  'StreamingMovies',
  'Contract',
  'PaperlessBilling',
  'PaymentMethod',
  'TotalCharges'])

In [6]:
for non_numeric_feature in non_numeric_features:
    display(df[non_numeric_feature].value_counts())

gender
Male      3555
Female    3488
Name: count, dtype: int64

SeniorCitizen
0    5901
1    1142
Name: count, dtype: int64

Partner
No     3641
Yes    3402
Name: count, dtype: int64

Dependents
No     4932
Yes    2110
Name: count, dtype: int64

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

MultipleLines
No                  3390
Yes                 2970
No phone service     682
Name: count, dtype: int64

InternetService
Fiber optic    3096
DSL            2420
No             1526
Name: count, dtype: int64

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

TechSupport
No                     3472
Yes                    2044
No internet service    1526
Name: count, dtype: int64

StreamingTV
No                     2809
Yes                    2707
No internet service    1526
Name: count, dtype: int64

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

PaperlessBilling
Yes    4170
No     2872
Name: count, dtype: int64

PaymentMethod
Electronic check             2363
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

TotalCharges
          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: count, Length: 6531, dtype: int64

In [7]:
df['TotalCharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...   
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: object

In [8]:
mask = df['TotalCharges'].map(lambda x: x.replace('.', '').isdigit() and x.count('.') < 2)
df['TotalCharges'][~mask]

488      
753      
936      
1082     
1340     
3331     
3826     
4380     
5218     
6670     
6754     
Name: TotalCharges, dtype: object

In [9]:
df['TotalCharges'] = df['TotalCharges'].map(lambda x: x.replace(' ', '')).map(lambda x: np.nan if x == '' else x).astype('float64')
df['TotalCharges'].describe()

count    7032.000000
mean     2283.300441
std      2266.771362
min        18.800000
25%       401.450000
50%      1397.475000
75%      3794.737500
max      8684.800000
Name: TotalCharges, dtype: float64

In [10]:
numeric_features = [feature for feature in features if feature in list(df.describe())]
non_numeric_features = [feature for feature in features if feature not in list(df.describe())]
numeric_features, non_numeric_features

(['tenure', 'MonthlyCharges', 'TotalCharges'],
 ['gender',
  'SeniorCitizen',
  'Partner',
  'Dependents',
  'PhoneService',
  'MultipleLines',
  'InternetService',
  'OnlineSecurity',
  'OnlineBackup',
  'DeviceProtection',
  'TechSupport',
  'StreamingTV',
  'StreamingMovies',
  'Contract',
  'PaperlessBilling',
  'PaymentMethod'])

In [11]:
df.isnull().mean()

customerID          0.000000
gender              0.000000
SeniorCitizen       0.000000
Partner             0.000000
Dependents          0.000142
tenure              0.000284
PhoneService        0.000000
MultipleLines       0.000142
InternetService     0.000142
OnlineSecurity      0.000000
OnlineBackup        0.000000
DeviceProtection    0.000000
TechSupport         0.000142
StreamingTV         0.000142
StreamingMovies     0.000000
Contract            0.000000
PaperlessBilling    0.000142
PaymentMethod       0.000284
MonthlyCharges      0.000000
TotalCharges        0.001562
Churn               0.000000
dtype: float64

In [12]:
for feature in numeric_features:
    median = df[feature].median()
    df[feature] = df[feature].fillna(median)
    
for feature in non_numeric_features:
    mode = df[feature].value_counts().index[0]
    df[feature] = df[feature].fillna(mode)
        
df.isnull().mean()

customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
Churn               0.0
dtype: float64

In [13]:
df['Churn'] = df['Churn'].map({'No': 0, 'Yes': 1})
df['Churn']

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [14]:
for non_numeric_feature in non_numeric_features:
    display(df[[non_numeric_feature, label]].groupby([non_numeric_feature]).mean())

Churn
gender          
Female  0.269209
Male    0.261603

Churn
SeniorCitizen          
0              0.236062
1              0.416813

Churn
Partner          
No       0.329580
Yes      0.196649

Churn
Dependents          
No          0.312791
Yes         0.154502

Churn
PhoneService          
No            0.249267
Yes           0.267096

Churn
MultipleLines             
No                0.250369
No phone service  0.249267
Yes               0.286195

Churn
InternetService          
DSL              0.189669
Fiber optic      0.418792
No               0.074050

Churn
OnlineSecurity               
No                   0.417667
No internet service  0.074050
Yes                  0.146112

Churn
OnlineBackup                 
No                   0.399288
No internet service  0.074050
Yes                  0.215315

Churn
DeviceProtection             
No                   0.391276
No internet service  0.074050
Yes                  0.225021

Churn
TechSupport                  
No                   0.416355
No internet service  0.074050
Yes                  0.151663

Churn
StreamingTV                  
No                   0.335231
No internet service  0.074050
Yes                  0.300702

Churn
StreamingMovies              
No                   0.336804
No internet service  0.074050
Yes                  0.299414

Churn
Contract                
Month-to-month  0.427097
One year        0.112695
Two year        0.028319

Churn
PaperlessBilling          
No                0.163301
Yes               0.335651

Churn
PaymentMethod                      
Bank transfer (automatic)  0.167098
Credit card (automatic)    0.152431
Electronic check           0.452854
Mailed check               0.191067

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encoder = LabelEncoder()

In [17]:
label_encoder.fit_transform(df['MultipleLines'])

array([1, 0, 0, ..., 1, 2, 0])

In [18]:
df_copy = df.copy()

In [19]:
for feature in non_numeric_features:
    df_copy[feature] = label_encoder.fit_transform(df_copy[feature])

In [20]:
df_copy

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0     7590-VHVEG       0              0        1           0     1.0   
1     5575-GNVDE       1              0        0           0    34.0   
2     3668-QPYBK       1              0        0           0     2.0   
3     7795-CFOCW       1              0        0           0    45.0   
4     9237-HQITU       0              0        0           0     2.0   
...          ...     ...            ...      ...         ...     ...   
7038  6840-RESVB       1              0        1           1    24.0   
7039  2234-XADUH       0              0        1           1    72.0   
7040  4801-JZAZL       0              0        1           1    11.0   
7041  8361-LTMKD       1              1        1           0     4.0   
7042  3186-AJIEK       1              0        0           0    66.0   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
0                0              1                0               0  ...   
1                1              0                0               2  ...   
2                1              0                0               2  ...   
3                0              1                0               2  ...   
4                1              0                1               0  ...   
...            ...            ...              ...             ...  ...   
7038             1              2                0               2  ...   
7039             1              2                1               0  ...   
7040             0              1                0               2  ...   
7041             1              2                1               0  ...   
7042             1              0                1               2  ...   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    0            0            0                0         0   
1                    2            0            0                0         1   
2                    0            0            0                0         0   
3                    2            2            0                0         1   
4                    0            0            0                0         0   
...                ...          ...          ...              ...       ...   
7038                 2            2            2                2         1   
7039                 2            0            2                2         1   
7040                 0            0            0                0         0   
7041                 0            0            0                0         0   
7042                 2            2            2                2         2   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                    1              2           29.85         29.85      0  
1                    0              3           56.95       1889.50      0  
2                    1              3           53.85        108.15      1  
3                    0              0           42.30       1840.75      0  
4                    1              2           70.70        151.65      1  
...                ...            ...             ...           ...    ...  
7038                 1              3           84.80       1990.50      0  
7039                 1              1          103.20       7362.90      0  
7040                 1              2           29.60        346.45      0  
7041                 1              3           74.40        306.60      1  
7042                 1              0          105.65       6844.50      0  

[7043 rows x 21 columns]

In [21]:
df_x = df_copy[non_numeric_features]
df_y = df_copy[label]

In [22]:
from sklearn.naive_bayes import CategoricalNB

In [23]:
gnb = CategoricalNB()

In [24]:
gnb.fit(df_x, df_y)
df_yhat = gnb.predict(df_x)

In [25]:
df_yhat

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [26]:
from sklearn import metrics

In [27]:
metrics.confusion_matrix(df_y, df_yhat)

array([[3510, 1664],
       [ 342, 1527]], dtype=int64)

In [28]:
excluded_features = ['gender', 'PhoneService', 'MultipleLines']

In [29]:
df_x = df_x.drop(excluded_features, axis=1)

In [30]:
gnb.fit(df_x, df_y)
df_yhat = gnb.predict(df_x)

In [31]:
metrics.confusion_matrix(df_y, df_yhat)

array([[3501, 1673],
       [ 342, 1527]], dtype=int64)